DELETE http://localhost:8080/api/students/2
###


POST http://localhost:8080/api/students
Content-Type: application/json

{
  "firstName": "Nagy",
  "lastName" : "C",
  "subjects" : ["MATH", "HISTORY"]
}

###
GET http://localhost:8080/api/students/room/2
Accept: application/json

###

GET http://localhost:8080/api/rooms/students/7
