
###
PUT http://localhost:8080/api/rooms/1
Content-Type: application/json
Accept: application/json

{
  "subject": "GERMAN"
}

###
GET http://localhost:8080/api/rooms/1
Accept: application/json

###

POST http://localhost:8080/api/rooms/create
Content-Type: application/json

{
  "number": 100,
  "capacity": 10
}
###
POST http://localhost:8080/api/rooms/create
Content-Type: application/json

{
  "number": 3,
  "capacity": 10
}

###
DELETE http://localhost:8080/api/rooms/2
